.eslintrc.js, .postcssrc.js, build/build.js, build/check-versions.js, build/dev-client.js, build/dev-server.js, build/utils.js, build/vue-loader.conf.js, build/webpack.base.conf.js, build/webpack.dev.conf.js, build/webpack.prod.conf.js, build/webpack.test.conf.js, config/dev.env.js, config/index.js, config/prod.env.js, config/test.env.js, test/e2e/custom-assertions/elementCount.js, test/e2e/nightwatch.conf.js, test/e2e/runner.js, test/unit/karma.conf.js
PhpStorm fixed some missing semicolons.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Clean code with PhpStorm

src/components/ListPanel/ListPanel.vue, src/components/ListPanel/ListPanelNotice.vue, src/components/ListPanel/submissions/CatalogSubmissionsListPanel.vue, src/components/ListPanel/submissions/SubmissionsListPanel.vue, src/components/SelectListPanel/SelectListPanel.vue, src/components/SelectListPanel/SelectListPanelItem.vue, src/components/SelectListPanel/SelectListPanelSelectAll.vue, src/components/SelectListPanel/submissions/SelectSubmissionsListItem.vue, src/components/SelectListPanel/submissions/SelectSubmissionsListPanel.vue, src/docs/examples/ListPanel/WithNotice.vue, src/docs/examples/ListPanel/data.js, src/docs/examples/ListPanel/implementations/ExampleCatalogSubmissionsListPanel.vue, src/docs/examples/SelectListPanel/WithSelectAll.vue, src/docs/examples/SelectListPanel/data.js, src/docs/examples/SelectListPanel/implementations/ExampleSelectSubmissionsListPanel.vue, src/docs/pages/elements.md, src/styles/elements/icons.less
- Adds SelectListPanelSelectAll component.
- Implements select all for submission list panels.
- Refactors ListPanel notices into ListPanelNotice component.
=> pkp/pkp-lib#2102 Implement SelectAll feature for SelectListPanel.

src/components/ListPanel/submissions/SubmissionsListItem.vue
s. https://github.com/pkp/pkp-lib/issues/3278
=> consider resubmit for review notices in the submission list

src/components/ListPanel/submissions/SubmissionsListItem.vue
Just replaced item.title by the localized title.
=> pkp/pkp-lib#4785 Fixes the modal with undefined title.

src/components/Form/fields/FieldPubId.vue
https://github.com/pkp/pkp-lib/issues/5254
=> Add publicationId as possible pubId component

src/components/Container/WorkflowContainer.vue, src/components/Form/Form.vue, src/components/Form/FormLocales.vue, src/components/Form/FormPage.vue, src/components/MultilingualProgress/MultilingualProgress.vue, src/docs/components/WorkflowContainer/previews/PreviewWorkflowContainer.vue
This collects commits from a number of PRs for separate issues, which were backed up due to problems with the old testing suite. Includes commits for the following issues:
https://github.com/pkp/pkp-lib/issues/5358#issuecomment-566520700
https://github.com/pkp/pkp-lib/issues/5355#issuecomment-566495080
https://github.com/pkp/pkp-lib/issues/5277#issuecomment-571541129
https://github.com/pkp/pkp-lib/issues/5236#issuecomment-571551600
https://github.com/pkp/pkp-lib/issues/5356#issuecomment-571689784
https://github.com/pkp/pkp-lib/issues/4858#issuecomment-572528377
https://github.com/pkp/pkp-lib/issues/4859#issuecomment-574264428
https://github.com/pkp/pkp-lib/issues/4868#issuecomment-574616770
https://github.com/pkp/pkp-lib/issues/4874#issuecomment-567915219 …
=> Several PRs for issues in 3.2

src/components/Form/fields/FieldSelect.vue
It fixes the freezing sidebar and need be applied with this PR https://github.com/pkp/ui-library/pull/71 to fix this issue https://github.com/pkp/pkp-lib/issues/5571
=> Fix browser freeze when sidebar selected #2

src/components/Form/fields/FieldBase.vue
=> Typo: MultilingualProgress

src/components/Form/fields/FieldRichTextarea.vue
@NateWr 
I have added the  logic to handle smarty variables into tinymce using a callback function.
This jsfiddle shows the functionality for it. 
https://fiddle.tiny.cloud/xyhaab
Issue [#122](https://github.com/pkp/orcidProfile/issues/122)
In SiteHandler.js there is also a [place](https://github.com/pkp/pkp-lib/blob/master/js/controllers/SiteHandler.js#L167), where tinymce is used , let me know, if that is still used  and the logic has to be added there too.
A small demo of the added functionality.
=> Handle smarty variables in Tinymce

src/components/ListPanel/submissions/SubmissionsListPanel.vue
Hi @NateWr,
Please review the changes and let me know if any issues.
Thanks
Salman
=> pkp/pkp-lib#6809 Add submissions filter by category

src/components/ListPanel/doi/DoiListPanel.vue
Expand error messaging and make DOI exception generic
=> pkp/pkp-lib#7518 Expand DOI bulk actions

src/components/Container/StatsPublicationsPage.vue
s. https://github.com/pkp/pkp-lib/issues/7318
=> fix getFilterDescription()

src/components/Container/StatsIssuesPage.vue, src/components/Container/StatsPublicationsPage.vue
s. https://github.com/pkp/pkp-lib/issues/8328
=> timeline report download

public/mailables.json
This PR aims to solve https://github.com/pkp/pkp-lib/issues/2135
=> pkp/pkp-lib#2135 Removed PASSWORD_RESET from mailable list

src/components/Form/FormGroup.vue, src/components/Form/fields/FieldRichText.vue, src/components/ListPanel/submissions/SubmissionsListItem.vue
This PR aims to add enhancement for pkp/pkp-lib#2564
=> pkp/pkp-lib#2564 Added html editor for title

src/components/Container/FailedJobDetailsPage.vue, src/components/Container/FailedJobsPage.vue, src/components/Container/JobsPage.vue, src/components/Table/Table.vue
This PR aims to provide solution for pkp/pkp-lib#8306
=> pkp/pkp-lib#8306 Failed jobs UI

src/components/Container/AccessPage.vue
=> pkp/pkp-lib#8734 Removed extra process call to handle bulk email sending

src/components/Container/CounterReportsPage.vue, src/components/Form/counter/CounterReportForm.vue, src/components/ListPanel/counter/CounterReportsListPanel.vue
s. https://github.com/pkp/pkp-lib/issues/8248
=> pkp/pkp-lib#8248 COUNTER R5 TSV reports

src/components/Form/fields/FieldOptions.stories.js, src/components/Form/fields/FieldOptions.vue, src/components/Form/mocks/field-options-onlySorting.js
s. https://github.com/pkp/pkp-lib/issues/9736
=> pkp/pkp-lib#9736 allow only sorting in FieldOptions 

src/components/ActionPanel/ActionPanel.mdx, src/components/ActionPanel/ActionPanel.stories.js, src/components/Badge/Badge.mdx, src/components/CodeHighlighter/CodeHighlighter.stories.js, src/components/Container/DecisionPage.stories.js, src/components/Container/ManageEmailsPage.stories.js, src/components/Container/Page.stories.js, src/components/Container/StatsPage.stories.js, src/components/Container/SubmissionWizardPage.stories.js, src/components/Container/WorkflowPage.stories.js, src/components/Dropdown/Dropdown.stories.js, src/components/FileAttacher/FileAttacher.mdx, src/components/FileUploader/FileUploader.mdx, src/components/Filter/Filter.mdx, src/components/Form/Form.mdx, src/components/Form/fields/FieldAutosuggestPreset.mdx, src/components/ListPanel/ListPanel.stories.js, src/components/Modal/Modal.mdx, src/components/Modal/Modal.stories.js, src/components/Orderer/Orderer.stories.js, src/components/Orderer/Orderer.vue, src/components/Pagination/Pagination.mdx, src/components/Pagination/Pagination.stories.js, src/components/Panel/Panel.stories.js, src/components/ProgressBar/ProgressBar.stories.js, src/components/Tooltip/Tooltip.stories.js, src/docs/guide/Accessibility.mdx, src/mixins/fetch.mdx, src/pages/acceptInvitation/AcceptInvitationPage.vue
Use PascalCase template naming for .mdx and story files.
=> pkp/pkp-lib#10153 Add additional vue eslint rules (Part 2)

src/components/Form/counter/CounterReportForm.vue
s. https://github.com/pkp/pkp-lib/issues/10350
=> pkp/pkp-lib#10350 fix the check of the COUNTER R5 form field customer_id

src/components/Form/fields/FieldOrcid.vue, src/components/ListPanel/contributors/ContributorsListPanel.vue
=> pkp/pkp-lib#10389 track author Orcid verification request state

src/composables/useSideMenu.js, src/composables/useSideMenu.mdx
=> pkp/pkp-lib#9890 Automatically update the expandedKeys when using setActiveItemKey in useSideMenu api

src/components/Container/SubmissionWizardPage.vue
=> pkp/pkp-lib#8350 Allow author to cancel submission

src/components/Form/fields/FieldAffiliations.vue, src/components/Form/fields/FieldAffiliationsRorAutoSuggest.vue
This PR is for issue https://github.com/pkp/pkp-lib/issues/10906
=> pkp/pkp-lib#10906 Entering duplicate ROR affiliations are not filtered from search results

src/components/Form/fields/FieldAffiliationsRorAutoSuggest.vue
=> pkp/pkp-lib#11188 Display country name in ROR results[main]

src/components/Form/fields/FieldAffiliationsRorAutoSuggest.vue
=> pkp/pkp-lib#11188 Display country name in ROR results [stable3.5]

public/globals.js, src/managers/UserInvitationManager/UserInvitationManagerCancelInvitationDialogBody.vue, src/managers/UserInvitationManager/UserInvitationManagerStore.js, src/pages/acceptInvitation/AcceptInvitationPageStore.js, src/pages/userInvitation/UserInvitationPageStore.js, src/pages/userInvitation/UserInvitationUserGroupsTable.vue
see https://github.com/pkp/pkp-lib/issues/11020 , https://github.com/pkp/pkp-lib/issues/11019, https://github.com/pkp/pkp-lib/issues/11018 , https://github.com/pkp/pkp-lib/issues/11017 , https://github.com/pkp/pkp-lib/issues/11037 , https://github.com/pkp/pkp-lib/issues/11037#issuecomment-2715586428, https://github.com/pkp/pkp-lib/issues/11021
=> fix issue and enhancements in GDPR invitations

src/components/Container/ManageEmailsPage.vue
For https://github.com/pkp/pkp-lib/issues/10571
=> pkp/pkp-lib#10571 Email access feature

src/components/Chart/LineChart.vue
s. https://github.com/pkp/pkp-lib/issues/11212
=> pkp/pkp-lib#11212 LineChart.vue y-axis beginAtZero

src/managers/UserAccessManager/UserAccessManagerStore.js, src/managers/UserInvitationManager/UserInvitationManagerStore.js, src/pages/userInvitation/UserInvitationExtendedMetaData.vue, src/pages/userInvitation/UserInvitationPage.vue, src/pages/userInvitation/UserInvitationPageStore.js
https://github.com/pkp/pkp-lib/issues/11118
=> update invitation page url and add separate  prop user extended meta data

src/managers/UserAccessManager/UserAccessManager.vue, src/managers/UserAccessManager/UserAccessManagerActionSearch.vue, src/managers/UserAccessManager/UserAccessManagerStore.js, src/managers/UserAccessManager/useUserAccessManagerActions.js, src/managers/UserAccessManager/useUserAccessManagerConfig.js
https://github.com/pkp/pkp-lib/issues/11273
=> improve user access manager extensibility

src/managers/ReviewerSuggestionManager/ReviewerSuggestionManager.vue
=> pkp/pkp-lib#10993 Reviewer Suggestion E2E test

src/components/ListPanel/contributors/ContributorsListPanel.vue, src/managers/GalleyManager/useGalleyManagerConfig.js, src/pages/workflow/WorkflowPageOJS.vue, src/pages/workflow/WorkflowPageOMP.vue, src/pages/workflow/WorkflowPageOPS.vue, src/pages/workflow/components/publication/WorkflowPublicationEditWarning.vue, src/pages/workflow/composables/useWorkflowConfig/workflowConfigEditorialOJS.js, src/pages/workflow/composables/useWorkflowPermissions.js
for [issue##10263](https://github.com/pkp/pkp-lib/issues/10263)
=> pkp/pkp-lib#10263 Relax editing metadata on published/posted materials

src/pages/userInvitation/UserInvitationPageStore.js
https://github.com/pkp/pkp-lib/issues/11265#issuecomment-2898507284
=> change invitation modal style

src/managers/CategoryManager/CategoryCellToggleSubCategories.vue
=> pkp/pkp-lib#11411 Update category tests

src/components/ListPanel/announcements/AnnouncementsListPanel.vue
=> pkp/pkp-lib#11556 Fix Expiry Date in Announcement form

src/pages/userComments/userCommentStore.js
=> pkp/pkp-lib#11771 Clear comments moderator table data when switching tabs
